// Generated by CoffeeScript 1.6.3
(function() {
  var gqmysql, o, o2, _;

  gqmysql = require("../../gqmysql2");

  _ = require("lodash");

  o = {
    connection: {
      host: "mysql",
      user: "admin",
      password: "mysql47284728",
      database: "db",
      route: "/api/db",
      table: "test"
    },
    key: {
      name: "test700"
    },
    data: {
      name: "test700",
      value: "666",
      fasthash: "D"
    },
    limit: 10
  };

  o2 = {
    connection: {
      host: "mysql",
      user: "admin",
      password: "mysql47284728",
      database: "db",
      route: "/api/db",
      table: "test"
    },
    key: {
      name: "test700"
    },
    data: {
      name: "test700",
      value: "999",
      fasthash: "D"
    },
    limit: 10
  };

  it("should be able to require", function(done) {
    gqmysql = require("../../gqmysql2");
    console.log("gqmysql2 required successfully");
    return done();
  });

  it("should be able to create", function(done) {
    return gqmysql.upsert(_.clone(o), function(e, o) {
      console.dir(o.result);
      return done(e);
    });
  });

  it("should not be able to create twice, but update", function(done) {
    return gqmysql.upsert(_.clone(o2), function(e, o) {
      console.dir(o.result);
      return done(e);
    });
  });

  it("should be able to find", function(done) {
    return gqmysql.find(_.clone(o), function(e, o) {
      console.dir(o.result);
      return done(e);
    });
  });

  it("should be able to delete", function(done) {
    return gqmysql["delete"](_.clone(o), function(e, o) {
      console.dir(o.result);
      return done(e);
    });
  });

  it("should not be able to delete twice", function(done) {
    return gqmysql["delete"](_.clone(o), function(e, o) {
      console.dir(o.result);
      return done(e);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
