// Generated by CoffeeScript 1.12.7
(function() {
  var _, getVal1, getVal2, gqmysql, o, val1, val2;

  gqmysql = require("../../gqmysql2");

  _ = require("lodash");

  val1 = Math.floor(Math.random() * 1000);

  val2 = val1 + 100;

  o = {
    connection: {
      host: "mysql",
      user: "root",
      password: "78567856",
      database: "db",
      route: "/api/db",
      table: "test"
    },
    key: {
      name: "test700"
    },
    data: {
      name: "test700",
      value: val1,
      fasthash: "D"
    },
    limit: 10
  };

  getVal1 = function() {
    return _.clone(o);
  };

  getVal2 = function() {
    var ret;
    ret = getVal1();
    ret.data.value = val2;
    return ret;
  };

  describe("should be able to ", function() {
    after(function(done) {
      process.exit(0);
      return done();
    });
    it("require", function(done) {
      gqmysql = require("../../gqmysql2");
      console.log("gqmysql2 required successfully");
      return done();
    });
    it("create", function(done) {
      return gqmysql.upsert(getVal1(), function(e, o) {
        console.dir(o.result);
        return done(e);
      });
    });
    it("not create twice, but update", function(done) {
      return gqmysql.upsert(getVal2(), function(e, o) {
        console.dir(o.result);
        return done(e);
      });
    });
    it("find", function(done) {
      return gqmysql.find(getVal1(), function(e, o) {
        console.dir(o.result);
        return done(e);
      });
    });
    it("delete", function(done) {
      return gqmysql["delete"](getVal1(), function(e, o) {
        console.dir(o.result);
        return done(e);
      });
    });
    return it("not delete twice", function(done) {
      return gqmysql["delete"](getVal1(), function(e, o) {
        console.dir(o.result);
        return done(e);
      });
    });
  });

}).call(this);
